FROM node:16 AS builder
ARG CONFIGURATION='production'
WORKDIR /app
COPY package.json  package-lock.json ./
RUN npm ci --legacy-peer-deps
COPY . .
RUN npm run build --  --output-path=dist --configuration=$CONFIGURATION --output-hashing=all


FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./.docker/nginx.conf /etc/nginx/conf.d/default.conf